name: Build & Push Strapi Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and Push
        run: |
          docker build -t pranidock/my-strapi-app:${{ steps.vars.outputs.sha_short }} .
          docker push pranidock/my-strapi-app:${{ steps.vars.outputs.sha_short }}

      - name: Set output image tag
        id: image
        run: echo "tag=${{ steps.vars.outputs.sha_short }}" >> $GITHUB_OUTPUT

    outputs:
      image_tag: ${{ steps.image.outputs.tag }}
